version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: node
    restart: always
    environment:
      - MYSQL_DATABASE=biblioteca
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3309:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local